### ISSUE TITLE
Site path cannot be AppDomain.CurrentDomain.BaseDirectory, it is readonly.

### ISSUE THREAD

**Issue by pazof** [SimplifyNet/Simplify.Web#175]
Using mono-service to start a web service, under Debian, led me to modify the `new Modules.Environment` invocation, 

as long, in this case, AppDomain.CurrentDomain.BaseDirectory points a system directory  (/usr/lib/mono/4.5), and this property is non-modifable.

So this value cannot be used as the site path. 
I prefered to use the current directory instead.

**To Reproduce**
1. Build a project of your own, embeded in a Windows service, displaying some template result
2. Use mono-service to lauch the service : `mono-service  -d:. -l:your.lock your.exe`
3. browse your page : the template is not found, it is searched from /usr/lib/mono/4.5

**Expected behavior**
The templates are found, because the site path is the current working dirrectory

**Desktop:**
 - OS: Debian Bullseye

**Comment by i4004** [comment]
As a quick solution you can modify `Environment` registration via custom bootstrapper and set your custom path: https://github.com/SimplifyNet/Simplify.Web/wiki/Custom-Simplify.Web-bootstrapper

```csharp
public class MyBootstrapper : BaseBootstrapper
{
    public override void RegisterEnvironment() =>
        BootstrapperFactory.ContainerProvider.Register<IEnvironment>(
				r => new Modules.Environment(Directory.GetCurrentDirectory(), r.Resolve<ISimplifyWebSettings>()));
}
```

**Comment by i4004** [comment]
I was able to reproduce that, but don't see a way to automatically switch between `AppDomain.CurrentDomain.BaseDirectory` and `Directory.GetCurrentDirectory()`.

Is it OK, if I create a Simplify.Web config setting (https://github.com/SimplifyNet/Simplify.Web/wiki/Simplify.Web-configuration) to switch between them?

**Comment by pazof** [comment]
> I was able to reproduce that, but don't see a way to automatically switch between `AppDomain.CurrentDomain.BaseDirectory` and `Directory.GetCurrentDirectory()`.
> 
> Is it OK, if I create a Simplify.Web config setting (https://github.com/SimplifyNet/Simplify.Web/wiki/Simplify.Web-configuration) to switch between them?

Registering your custom bootstrapper is a solution for my use case.
The architecture seems flawless to me, after all. 

For me, you can close this topic.

**Comment by pazof** [comment]
Registering your custom bootstrapper is a solution for my use case.
The architecture seems irreproachable to me, you can close this topic.
