### ISSUE TITLE
MinAttribute and MaxAttribute don't work in request view models

### ISSUE THREAD

**Issue by yollosun** [SimplifyNet/Simplify.Web#256]
**Describe the bug**
error CS0181: Attribute constructor parameter 'min
Value' has type 'IComparable', which is not a valid attribute parameter type

This is a CLR restriction. Only primitive constants or arrays of primitives can be used as attribute parameters. The reason why is that an attribute must be encoded entirely in metadata. 

**Expected behavior**
I need to use attributes in request view models.
(https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/attributes#attribute-parameter-types)

**Screenshots**
![image](https://github.com/SimplifyNet/Simplify.Web/assets/75416460/42e0a70e-4cca-4fd2-ab24-3e2bf2d10422)

**Comment by yollosun** [comment]
@i4004 

It seems to me that making a constructor for each type will not be very convenient because it will be necessary to use it like this
<img width="277" alt="image" src="https://github.com/SimplifyNet/Simplify.Web/assets/75416460/00c28d86-ee8a-4c0d-bdda-991b2b5ff6ae">

what do you think about microsoft implementation?
we can convert all value to int or double and when we need to use specified type we can provide value in string type and type in which we want convert
For ex: 
[Max(typeof(long), "25")]

https://github.com/Microsoft/referencesource/blob/master/System.ComponentModel.DataAnnotations/DataAnnotations/RangeAttribute.cs

**Comment by i4004** [comment]
I think this will be enough:

```csharp
	[Max(1)]
	public int IntParam { get; set; }

	[Max((long)1)]
	public long LongParam { get; set; }

	[Max(1d)]
	public double DoubleParam { get; set; }

	[Max(typeof(decimal), "12.5")]
	public decimal DecimalParam { get; set; }
```
